### ISSUE TITLE
Remarks on security

### ISSUE THREAD

**Issue by techsolo** [open-ch/log-user-session#11]
Our security engineer had a look at the solution and this are his remarks.

* Logging can be bypassed if the user uses ‘screen’ or ‘tmux’
Activity is not recorded
* ANSI code at user output are making logs inoperable
E.g.: Use of VIM with color syntaxing activated makes the output unreadable. Can be tested, for example, to set an alias  with VIM (e.g. ‘rm -rf /’), not possible to track.
* ANSI recording generates enormous log files.
Color info is not mandatory in the logs

Anything you can agree on and want to remediate?

**Comment by markstos** [comment]
> * Logging can be bypassed if the user uses ‘screen’ or ‘tmux’

This is worth noting in the documentation, but I don't see it as a dealbreaker.

A bastion host with public SSH access has no need to have to `screen` or `tmux` installed.

> * ANSI code at user output are making logs inoperable

Are the logs ugly or broken?

> * ANSI recording generates enormous log files.

Again, on a bastion host users will normally only be SSHing through, generating little to no logging.

If a malicious gets in, you've got bigger problems then the size of the log file.

The documentation could also stand to be updated that [logs nothing when user's use the host as an SSH proxy](https://github.com/open-ch/log-user-session/issues/3).  As noted in that ticket, the incoming IP address is captured in other logs, but the outgoing host that's proxied to is not captured.

**Comment by nimdanitro** [comment]
@techsolo Thanks for your report. I've got some follow up questions.

> Logging can be bypassed if the user uses ‘screen’ or ‘tmux’
> Activity is not recorded

log-user-sessions records every input and output of the user shell, i.e. also screen and tmux inputs and outputs. However, screen and tmux makes heavy use of ANSI codes, i.e. to clear screens, resize, move cursors, etc.. Depending on how you look at the generated log files, you don't see the actions performed, i.e. a simple `cat $logfile` will detect the ANSI codes and perform their actions in your shell. If you have a look at the raw logs (i.e. not interpolating the ANSI codes, you all input / output of screen and tmux sessions). 

How exactly do you come to the conclusion that the activity is not recorded? Please provide us the steps to reproduce this.

> ANSI code at user output are making logs inoperable
> E.g.: Use of VIM with color syntaxing activated makes the output unreadable. Can be tested, for  example, to set an alias with VIM (e.g. ‘rm -rf /’), not possible to track.

Same here, you would be able to look at the raw logs and see that the user execute macro/ alias X.

> Yes, ANSI recording generates some overhead in the file but this information is crucial to have a full audit of the session. Color information is only a small subsection of all ANSI sequences.

**Comment by kbucheli** [comment]
I added a hint to the manpage about the interpretation of the ANSI codes by the terminal and the recommendation to use a standalone viewer/editor to look at the log file.
