### ISSUE TITLE
log-user-sessio segfault

### ISSUE THREAD

**Issue by yangliping** [open-ch/log-user-session#15]
Hi,

There are a few segmentation fault in the /var/log/messages log. How can I debug this problem?

```
Apr  4 05:00:12 test-f kernel: log-user-sessio[66297]: segfault at 0 ip 0000000000402669 sp 00007ffe203fb570 error 4 in log-user-session[400000+5000]
Apr  4 05:02:03 test-f kernel: log-user-sessio[66448]: segfault at 0 ip 0000000000402669 sp 00007ffe28fff010 error 4 in log-user-session[400000+5000]
Apr  4 05:07:23 test-f kernel: log-user-sessio[66951]: segfault at 0 ip 0000000000402669 sp 00007fff400137d0 error 4 in log-user-session[400000+5000]
```

**Comment by nimdanitro** [comment]
Well, basically gdb is a good start. What version are you using?

**Comment by yangliping** [comment]
log-user-session: Release 0.8
OS: CentOS Linux release 7.6.1810 (Core)
kernel: 3.10.0-957.10.1.el7.x86_64 x86_64

Do you have more specific steps on using gdb to debug? Thanks.

**Comment by kbucheli** [comment]
1) have the tool built with debug symbols
2) run the tool until it runs into a segfault and creates the core dump
    https://linux-audit.com/understand-and-configure-core-dumps-work-on-linux/
3) debug the core dump with gdb
   https://stackoverflow.com/questions/8305866/how-to-analyze-a-programs-core-dump-file-with-gdb

**Comment by yangliping** [comment]
I can't reproduce the issue now. So close it.
