### ISSUE TITLE
Terminal gets garbled

### ISSUE THREAD

**Issue by evg-zhabotinsky** [open-ch/log-user-session#16]
Steps to reproduce:

1. Start `log-user-session`
2. In it, start `tmux`
3. Create a horizontal split (`^B` `%` by default)
4. Run `htop` (in the right pane)
5. Observe the left pane getting ruined

Other apps may break too.

**Comment by markstos** [comment]
Why could this package interfere with `tmux` usage?

**Comment by evg-zhabotinsky** [comment]
Well, it passes all the PTY IO through itself, and apparently loses some of it in process.

**Comment by nicm** [comment]
This program does not remove OPOST from c_oflags when it configures the external pty so output processing (by default ONLCR) will still be applied even when the application inside (tmux) turns it off.

It is probably enough to just turn it off on the master as well.

Alternatively, *BSD provides a way (TIOCPKT_IOCTL) to monitor for termios(4) changes - perhaps there is an equivalent on Linux.

~~~~
diff --git a/src/log-user-session.c b/src/log-user-session.c
index 55c3789..8c9f734 100644
--- a/src/log-user-session.c
+++ b/src/log-user-session.c
@@ -590,6 +590,7 @@ void set_raw_input(int fd, struct termios *old_term) {
      *       No 8th-bit stripping or parity error handling.
      *       Disable START/STOP output flow control. */
     tnew.c_iflag &= ~(BRKINT | ICRNL | IGNBRK | IGNCR | INLCR | INPCK | ISTRIP | IXON | PARMRK);
+    tnew.c_oflag &= ~OPOST;
 
     tcsetattr(STDIN_FILENO, TCSAFLUSH, &tnew);
 }

**Comment by kmeaw** [comment]
I can confirm that this patch makes the problem go away.
