### ISSUE TITLE
do not print error if configuration file is missing

### ISSUE THREAD

**Issue by markstos** [open-ch/log-user-session#2]
After a clean install and login, the user logging in is greeted with this:

```
using default configuration
/etc/log-user-session.conf: No such file or directory
```

I thought this might just happen on the first login, but it happens on every login. 

I tried just "touch"'ing the named file, but that just caused a different error. Apparently an empty file is not valid:

```
error while parsing configuration file /etc/log-user-session.conf:
```

Finally, I copied the defaults from the documentation and put them in the file. Since the defaults were used, the configuration was the same, but now there's no extra ouput when logging in. 

It would be nice if the configuration file was created during installation to avoid these warnings. 

Thanks!

**Comment by kbucheli** [comment]
The idea is that no configuration is needed. The file is only if you have some reason to change the default configuration. So I consider this a bug.

**Comment by kbucheli** [comment]
What do you think about the "using default configuration" greeting?
On a second thougth I find it somehow disturbing.

I think I should remove it.

Or maybe show a more useful message if there is no configuration file and no log directory. The log directory is automatically created, so that message would only be printed on the very first connection.

**Comment by markstos** [comment]
I agree that printing the message once on the first connection seems
appropriate. After that it seems like debug output.

On Fri, Feb 27, 2015 at 5:39 AM, Konrad Bucheli notifications@github.com
wrote:

> What do you think about the "using default configuration" greeting?
> On a second thougth I find it somehow disturbing.
> 
> I think I should remove it.
> 
> Or maybe show a more useful message if there is no configuration file and
> no log directory. The log directory is automatically created, so that
> message would only be printed on the very first connection.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/open-ch/log-user-session/issues/2#issuecomment-76374271
> .

## 

```
Mark Stosberg
Senior Systems Engineer
RideAmigos
```
