### ISSUE TITLE
grep'ing the log files can cause recursive logging loop

### ISSUE THREAD

**Issue by markstos** [open-ch/log-user-session#4]
I wanted to check the logs for something so I  became root and then ran a basic 'grep' on the log files. It matched the log file that was currently created, adding a new line to file which contained the grep command, including the word being grep'ed for. This happened fast enough  to be displayed as an additional match for grep, which caused another line to be written and another match to be found and another line to be written and...

The log grew 100x in size in just a few seconds before I manually cancelled the grep. 

If this is not fixable, the possibility should be noted in the documentation.

**Comment by kbucheli** [comment]
It is inherent to the problem. There is no way to detect this without breaking transparency. But a warning in the documentation is a good point.

**Comment by markstos** [comment]
Might this be improved on systemd-based systemd by logging directly to the systemd journal? As a binary format, it's immune to most accidental grep'ing of /var/log.

**Comment by kbucheli** [comment]
Do you know about 'journalctl -f'? This problem is inherent in the use case, using a different tool to do the same does not help.

**Comment by markstos** [comment]
I'm aware of the command to follow the journal, but it's much more frequent that I grep all the logs, the likelihood of a problem is reduced.
