### ISSUE TITLE
using exec on .bashrc

### ISSUE THREAD

**Issue by ghost** [open-ch/log-user-session#7]
I'm calling a menu from .bashrc using exec command. Seems like log-user-session does not start at all, no file is generated in this case.

**Comment by kbucheli** [comment]
What do you exactly do (shell code)?

**Comment by ghost** [comment]
Actually I get it now working. menu.sh is simple script, first answer from http://askubuntu.com/questions/1705/how-can-i-create-a-select-menu-in-a-shell-script

Before I had in .bashrc, no log was generated at all.
exec ./menu.sh

and I changed it to 
exec /usr/local/bin/log-user-session ./menu.sh

Now it works. My idea is to force user to do only what is available in menu and also log everything. I think it works now and is secure too. log-user-session is very good program, thank you very much!

**Comment by kbucheli** [comment]
Yes, with your second version it should work.
