### ISSUE TITLE
command 'stty -echo' allows escape session logging easily!

### ISSUE THREAD

**Issue by cypa** [open-ch/log-user-session#8]
As I found script, asciinema or log-user-session is not enough for security audit puposes since user typed input is not recorded until it is echoed by shell.
Thus if one issue command 'stty -echo' then all executed command became hidden so user escape security logging!

Do we need total recording of entire input/output by sshd?

**Comment by cypa** [comment]
I guess we have to use conspy tool for pty device to record session

**Comment by kbucheli** [comment]
I would accept a pull request which would support the 
```
LogInteractiveInput = 1 
```
configuration option

**Comment by cypa** [comment]
btw, how much log-user-session differs from script/scriptreplay from gnu-utils?

**Comment by kbucheli** [comment]
Out of my mind I know about following differences
- the log-user-session process runs as user root (setuid) and thus the user itself cannot tamper it
- with script you can also store timing information
- you can use log-user-session directly as ForcedCommand in the sshd configuration and it will handle remote commands or set up the TTY and the login shell and forwards terminal window resize events

**Comment by cypa** [comment]
FreeBSD version of script sipmpy adding input keys to log, so it looks like
$ccaatt foo
instead of 
$cat foo

**Comment by cypa** [comment]
but, finally, I guess one needs network traffic logging fo security reasons, cause there is port forwarding and many other tricks in sshd ...

**Comment by kbucheli** [comment]
It depends on your use case or what you want to achieve. The tool log-user-session does not store everything on purpose. 
For interactive sessions the input is not stored as it is echoed by the shell, except for passwords. And especially these we do not want to be stored. When auditing a 'stty -echo' still is visible, and also the rest of output of the hidden commands. It is as suspicious as if you get a script with wget and execute it.

By default also the output of non-interactive sessions is not recorded as it mostly contains uninteresting binary stuff by scp or rsync. But the command as such is recorded, so it does not happen in stealth. But unlike the input you many change that with the LogNonInteractiveData configuration option.

Indeed, if you want to record all traffic over sshd, then you need to go inside. This tool is only for shell session.
